Repository tracked-tools/tracked-maps-and-sets, pull requests merged in 2021-05, with the labels that each got.

#28 Fixed the root level undefined
  src/-private/util.ts
Labels: bug

#31 Config updates: CI, linting, and Volta
  .eslintrc.js
  .github/workflows/CI.yml
  .prettierrc.js
  .travis.yml
  config/ember-try-typescript.js
  config/ember-try.js
  package.json
  yarn.lock
Labels: internal

#34 Fix branch targets in CI.yml
  .github/workflows/CI.yml
  package.json
  yarn.lock
Labels: dependencies, internal

#39 Bump all @types/* dependencies to latest
  package.json
  yarn.lock
Labels: dependencies, internal

#42 Type check all TS versions since 3.7 in CI
  .github/workflows/CI.yml
  config/ember-try-typescript.js
Labels: enhancement, internal

#43 Bump release-it dependencies to latest
  package.json
  yarn.lock
Labels: dependencies, internal

#44 Switch to `prepare` npm script
  package.json
Labels: internal

#45 Bump to TS 4.2.4 for dev
  package.json
  yarn.lock
Labels: dependencies, internal

#46 Bump to latest @typescript-eslint/parser
  package.json
  yarn.lock
Labels: dependencies, internal
